---
output: github_document
always_allow_html: yes
---

```{r, load-libs, echo=FALSE, message=F, warning=F}
library(dplyr) 
library(tidyr)
library(gt)
library(ggplot2)
library(readr)
library(knitr)
library(kableExtra)
library(here)
```

```{r, load-table, echo=F, message=F}
# Load table
os_table <- read_csv(here("data", "os_data.csv"))
```


```{r, add-entry, echo=FALSE, eval=FALSE}
# Add new entries
new_entry <- tibble(
  Authors = "Roettger, Mahrt, and Cole", 
  Year = 2019, 
  Title = "Mapping prosody onto meaning – the case of information structure in American English", 
  Journal = "Language, Cognition and Neuroscience", 
  `Data available` = 1, 
  `Code available` = 1, 
  Notes = "Perception of prosody with regard to information structure.", 
  Links = "[article](https://timo-roettger.weebly.com/uploads/1/0/0/6/100641454/roettger_mahrt_cole__2019_._mapping_prosody_onto_meaning_the_case_of_information_structure_in_american_english.pdf)  [code](https://osf.io/4qxmh/)", 
  Citation = "Roettger, T. B., Mahrt, T., & Cole, J. (2019): Mapping prosody onto meaning – the case of information structure in American English, Language, Cognition and Neuroscience"
) %>% 
  write_csv(., here("data", "os_data.csv"), append = TRUE)
```


```{r, create-table, echo=F}
# Create GT table (not working w/ github)
os_table %>% 
  arrange(., desc(Year), Citation) %>% 
  select(., Citation, `Data available`, `Code available`, Notes, Links) %>% 
  kable(., format = "markdown") %>% 
  #kable_styling(., position = "center", font_size = 9, 
  #                 bootstrap_options = "striped") %>% 
  {.}
```
